### ISSUE TITLE
Review Notes

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/fin-ad-base-theme#1]
Howdy! :) I'm leaving some notes here while working through the theme review.
- `page.php` is a duplicate of the Spine Parent Theme. I would recommend removing it from the child theme.
- `template-builder.php` is also a duplicate. I would recommend removing it from the child theme.
- The `spine_show_builder_page_template_custom()` function and filter adding would have already been taken care of at the Spine parent theme level, so can be removed even though a custom builder is being used.
- The `WSU_FinAd_BaseTheme` class is only needed if you'll be using that to load hooks and manage logic. In its current state, it can be removed.
- It looks like the `side-right.php`, `side-left.php`, and `single.php` templates are the only ones that modify the original Spine Parent Theme versions. I would recommend deleting the others from the child theme.
- A couple methods are called as static even though they aren't. Example: `Fais_Spine_Builder_Custom::build_flexwork_sectional_inputs`. It may be good to adjust that to `Fais_Spine_Builder_Custom->build_flexwork_sectional_inputs`.
- The "Flexwork class builder" is interesting, though I will encourage some caution. I don't know how tied into existing functionality it is, but we'll have a hard time guaranteeing backwards compatibility with some of the styles and positioning of that modal. I doubt this will be that much of an issue, but keep your eyes on the Spine Parent Theme traffic for changes that may impact. We'll try to do the same.

**Comment by quantumJLBass** [comment]
Yep, the duplicates are from the initial setup, but are on the list of the clean up, we just needed to get some of the parts vetted out.  The `WSU_FinAd_BaseTheme` is just a stub right now but it is planned to have a little logic, so why it is there.  

I will be watching as well for changes that will affect the new options, so that is not lost on this.  The clean up will be happening soon after we get a few more details finalized.

**Comment by quantumJLBass** [comment]
all points were address so closing
